In [1]:
import lyncs_io as io
import gluon_utils as utils

import numpy as np

In [65]:
Nt = 16
vtype = "VR"

In [66]:
conf_path = f"../gauge_confs/confs/vortex-{'only' if vtype in ['VO','VOS'] else 'removed'}/{Nt}x32/Gen2l_{Nt}x32n1-{vtype}"
conf_path

'../gauge_confs/confs/vortex-removed/16x32/Gen2l_16x32n1-VR'

In [67]:
data = io.load(conf_path,format='openqcd')

In [68]:
lattice = utils.lattice(data,(Nt,32,4,3))

In [69]:
lattice.lattice

array([[[[[[[-6.89635436e-01+2.35476725e-01j,
              3.54609381e-01+3.62525594e-01j,
              4.58013596e-01-4.47727992e-02j],
            [-4.74383325e-02+3.89893906e-01j,
             -6.54528555e-01+5.14088671e-01j,
             -2.04627804e-01-3.33414182e-01j],
            [ 3.25074024e-01+4.57179290e-01j,
             -2.23900624e-01+1.04849258e-03j,
              4.88498767e-01+6.29722432e-01j]],

           [[ 5.86515755e-01-3.24921712e-01j,
              3.56751613e-01+4.37420783e-01j,
             -4.80904861e-01+2.33882339e-02j],
            [ 3.24323629e-01+8.95834027e-02j,
             -2.40750248e-01+2.85343317e-01j,
              4.51813174e-01+7.37070121e-01j],
            [-2.70328999e-01-6.03437138e-01j,
             -6.62549638e-01+3.20995065e-01j,
             -1.25006910e-01-7.17584141e-02j]],

           [[-2.18767115e-01+3.43123147e-01j,
             -7.41759223e-01+3.08131956e-01j,
             -3.04642639e-01+3.10561219e-01j],
            [ 6.9247390

In [70]:
lattice.evaluate_divA()

17.092299268416067

In [72]:
utils.decompose_su3(lattice.lattice[0,1,1,1,0])

array([-0.29770712+0.j        , -0.23622247+0.j        ,
       -0.12316807-0.07323021j,  0.46390282+0.j        ,
       -0.11012035+0.j        , -0.51823991+0.j        ,
       -0.04088664+0.j        ,  0.16230523+0.j        ])

In [63]:
U = lattice.lattice[0,0,0,1,0]
U

array([[-0.36476752+0.07991328j,  0.0469001 -0.79250298j,
         0.47980832+0.00905083j],
       [ 0.78559408+0.21511302j,  0.33084862-0.40368289j,
        -0.13363803-0.21514767j],
       [-0.33917039-0.28651404j,  0.30904765-0.04252386j,
        -0.29574536-0.78618643j]])

In [64]:
np.exp(2j*2*np.pi/3)

(-0.5000000000000004-0.8660254037844384j)

In [51]:
np.sin(2*np.pi/3)

0.8660254037844387

In [52]:
lattice.get_A([0,2,1,4],1)

array([[ 0.19513985+0.j        , -0.15302477+0.21940068j,
         0.15705257-0.14522727j],
       [-0.15302477-0.21940068j, -0.44020326-0.j        ,
         0.08405791+0.03610893j],
       [ 0.15705257+0.14522727j,  0.08405791-0.03610893j,
         0.24506341+0.j        ]])

In [14]:
U

array([[-0.36476752+0.07991328j,  0.0469001 -0.79250298j,
         0.47980832+0.00905083j],
       [ 0.78559408+0.21511302j,  0.33084862-0.40368289j,
        -0.13363803-0.21514767j],
       [-0.33917039-0.28651404j,  0.30904765-0.04252386j,
        -0.29574536-0.78618643j]])

In [15]:
utils.tracelessHermConjSubtraction(U)

array([[ 0.        +0.89979725j, -0.73869399-0.57738995j,
         0.8189787 -0.27746322j],
       [ 0.73869399-0.57738995j,  0.        -0.06739508j,
        -0.44268569-0.25767153j],
       [-0.8189787 -0.27746322j,  0.44268569-0.25767153j,
         0.        -0.83240217j]])

In [16]:
U - np.conj(U)

array([[0.+0.15982655j, 0.-1.58500595j, 0.+0.01810165j],
       [0.+0.43022605j, 0.-0.80736577j, 0.-0.43029534j],
       [0.-0.57302809j, 0.-0.08504773j, 0.-1.57237286j]])

In [17]:
np.trace(U-np.conj(U))/3

-0.7399706925393158j